name: BlockMania
#Major update, secondary update,  patches
version: '1.3.1'
main: me.troldepus2005.blockmania.Main
api-version: 1.18
authors: [ Troldepus2005 ]
load: startup
depend:
  - WorldGuard
commands:
  Blockmania:
    description: Blockmania standard command
